version: '3.1'
services:
  graphql_backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
    container_name: graphql_backend
    depends_on:
      - "db"
  db:
    image: mariadb
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
